### PR TITLE
feat: text-rotation

### PR DESCRIPTION
**Pull request by AlexisLeite**
Added the textRotation property to CellStyle and implemented functionality as described in the following link: https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.alignment?view=openxml-2.8.1.

Specifically:

```
textRotation (Text Rotation)	Text rotation in cells. Expressed in degrees. Values range from 0 to 180. The first letter of the text is considered the center-point of the arc.

For 0 - 90, the value represents degrees above horizon. For 91-180 the degrees below the horizon is calculated as:

[degrees below horizon] = 90 - textRotation.

0

f889d30a-8375-439a-9e0b-56ff52fbd5b5

45

872e3366-0bf4-46f0-a13a-68fab0e628a6

90

9ac50fd5-afdb-4e40-b324-88936a683e18

135

8135bb3c-b0ff-4df7-addd-1bbe447eacda

180

9c9f7ca0-6b7a-45a4-b699-36685b67471b

The possible values for this attribute are defined by the W3C XML Schema unsignedInt datatype.
```

### CODE REVIEW

**Comment by catamphetamine** [comment]
Hmm, interesting. I can see you've implemented it correctly.

I was thinking if we should expose it as is — as `textRotation` — or should we call it something different.

I'd suggest `textOrientation`, following CSS "rule" naming:
https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation

The possible values for it would then be `horizontal` (default) or `vertical` (your case).

I'll merge your changes tomorrow, fix a couple of small syntax issues, add a test, add README docs and I guess I'll publish a new version then.
Thanks for the solution.

**Comment by AlexisLeite** [comment]
That's a really good idea. In fact, I had the same thought. Both properties, 'textOrientation' and 'textRotation', can be exposed, with 'textOrientation' potentially serving as a wrapper around 'textRotation'.

Anyway, I'm fine with whichever approach you think is better. Thanks for your time; I find this library very useful. You've done excellent work.

If you're open to collaboration in further improving it, I might be able to help. Please let me know what your plans are for this library. Thanks!

**Review by catamphetamine — APPROVED** [review]
After reading a bit more on text rotation property in XLSX, seems like your suggestions are the way to go, so I'm merging this as is.

**Comment by catamphetamine** [comment]
Published `write-excel-file@1.4.28`

**Comment by AlexisLeite** [comment]
I'm glad to hear that. Thank you

A last thing: in the docs, you said that the correct values are -90 to 90. However, in the specs I found, it said that the range goes from 0 to 180, with 90 to 180 representing -90 to 0. Check the following quote:

> For 0 - 90, the value represents degrees above horizon. For 91-180 the degrees below the horizon is calculated as:

Let's keep in touch! Cheers

**Comment by catamphetamine** [comment]
> However, in the specs I found, it said that the range goes from 0 to 180, with 90 to 180 representing -90 to 0. 

Yeah, I've searched for the spec details on that one and didn't really find any "source of truth".
Seems like different libraries all do that part differently.

Here, it showcases only -90 to 90
https://docs.closedxml.io/en/latest/features/cell-format.html#orientation

Here, it's -90 to 90 or 270 as a special magic value
https://xlsxwriter.readthedocs.io/format.html#format-set-rotation

In Apache POI, it's also -90 to 90 or 255 as a special magic value
https://copyprogramming.com/howto/how-to-rotate-text-in-a-spreadsheet-cell-using-apache-poi

>  Specify the angle of rotation for the text within the cell.
The degree of rotation can range between -90 and 90 degrees, or it can be set to 0xff for vertical alignment. 

So seems that there's no consensus on that one over the internet, and -90 to 90 just seems like a "safe" common-practice value range.

**Comment by AlexisLeite** [comment]
I mentioned this detail because when I tried setting the value to -90, it didn't work. However, setting it to 180 achieved the expected effect that -90 was supposed to produce. 

I believe it would be more appropriate for the range to accept values from -90 to 90, with the library internally adjusting the values to ensure they work correctly. 

Alternatively, another option could be to set the property range from 0 to 180. 

This is just a suggestion, though. Since the input is numerical, one can simply enter the most suitable value.

**Comment by catamphetamine** [comment]
Hmm, 180 deg would be strange because wouldn’t it simply rotate the text
upside down? That’s not the same as 90 or -90.

You can see how quickly it becomes confusing with xlsx. That’s why I’m not
really adding any new features. I tend to leave it as -90 to 90 and not
research any further.

**Comment by AlexisLeite** [comment]
I agree that the xlsx format is confusing in its specification, primarily because there is no single source of truth. Despite this, the documentation I found was accurate and functioned as expected.

The working value ranges from 0 to 180, tested with Google Sheets, Microsoft Excel, and Trio Office. The final decision is yours. Regards.

**Comment by catamphetamine** [comment]
@AlexisLeite Oh, I see. Actually, I didn't read your original comment in this PR because we've been talking in a corresponding GitLab issue prior to that. So I just skipped it. Looking at it now, it looks like you've found the actual official specification for the `textRotation` parameter, which I didn't find when I googled `textRotation`. From that official documentation, it's now clear that they use an even weirder way of calculating the actual rotation angle. No wonder the open-source libraries use their own representation of `-90...90`. I've changed the code so that it re-calculates the value according to the spec, so it seems to be working now. Published `write-excel-file@1.4.29`.

**Pull request merged**
